const InventoryData = [
  {
    Id: 2566,
    Name: "Deinm Jeans",
    SKU: "DJ-CL-2566",
    Image:require('../Pages/Assets/Denim_Jeans.jpg'),
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Bottoms",
    Brand: "Dein Apparel",
    gender: "Male",
    variants: [
      { color: "Blue", sizes: { S: 10, M: 20, L: 15, XL: 5 } },
      { color: "Black", sizes: { S: 5, M: 10, L: 10, XL: 5 } }
    ],
    warehouseId: 1,
    aisle: "A3",
    row: "R2",
    shelf: "S5",
    bin: "B12",
    stock: 90,
    reserved: 20,
    available: 70,
    price: 2500,
    currency: "INR",
    batchNumber: "B202601",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 2567,
    Name: "Classic White Tee",
    SKU: "DJ-CL-2567",
    Image:require('../Pages/Assets/White_Tee.jpg'),
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Tops",
    Brand: "Park Avenue",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { S: 15, M: 25, L: 20, XL: 10 } },
      { color: "Grey", sizes: { S: 10, M: 15, L: 10, XL: 5 } }
    ],
    warehouseId: 2,
    aisle: "A3",
    row: "R1",
    shelf: "S4",
    bin: "B10",
    stock: 120,
    reserved: 15,
    available: 105,
    price: 999,
    currency: "INR",
    batchNumber: "B202602",
    serialNumbers: [],
    rating: 4.0,
  },
  {
    Id: 2568,
    Name: "Floral Summer Dress",
    SKU: "DJ-CL-2568",
    Image:require('../Pages/Assets/Floral_Summer.jpg'),
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Dresses",
    Brand: "Twills",
    gender: "Female",
    variants: [
      { color: "Yellow", sizes: { S: 5, M: 10, L: 8 } },
      { color: "Pink", sizes: { S: 8, M: 12, L: 10 } }
    ],
    warehouseId: 3,
    aisle: "A1",
    row: "R3",
    shelf: "S2",
    bin: "B5",
    stock: 53,
    reserved: 10,
    available: 43,
    price: 1799,
    currency: "INR",
    batchNumber: "B202603",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 2569,
    Name: "Leather Biker Jacket",
    SKU: "DJ-CL-2569",
    Image:require('../Pages/Assets/Leather_Jacket.jpg'),
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Outerwear",
    Brand: "Dein Apparel",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { S: 5, M: 10, L: 10, XL: 5 } },
      { color: "Brown", sizes: { S: 3, M: 5, L: 5, XL: 2 } }
    ],
    warehouseId: 3,
    aisle: "A2",
    row: "R4",
    shelf: "S3",
    bin: "B8",
    stock: 45,
    reserved: 5,
    available: 40,
    price: 5999,
    currency: "INR",
    batchNumber: "B202604",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 2570,
    Name: "Gym Leggings",
    SKU: "DJ-CL-2570",
    Image:require('../Pages/Assets/Gym_Leggings.jpg'),
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Activewear",
    Brand: "Prisma",
    gender: "Female",
    variants: [
      { color: "Black", sizes: { S: 10, M: 15, L: 10 } },
      { color: "Grey", sizes: { S: 8, M: 10, L: 7 } }
    ],
    warehouseId: 2,
    aisle: "A4",
    row: "R2",
    shelf: "S1",
    bin: "B7",
    stock: 60,
    reserved: 10,
    available: 50,
    price: 1499,
    currency: "INR",
    batchNumber: "B202605",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 2571,
    Name: "Running Sneakers",
    SKU: "DJ-FW-2571",
    Image:require('../Pages/Assets/Running_Sneakers.jpg'),
    Department: "Fashion",
    Category: "Footwear",
    subcategory: "Sneakers",
    Brand: "Nike",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { 6: 5, 7: 10, 8: 8, 9: 5 } },
      { color: "Black", sizes: { 6: 3, 7: 5, 8: 4, 9: 3 } }
    ],
    warehouseId: 1,
    aisle: "B1",
    row: "R1",
    shelf: "S3",
    bin: "B2",
    stock: 43,
    reserved: 10,
    available: 33,
    price: 3499,
    currency: "INR",
    batchNumber: "B202606",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 2572,
    Name: "Leather Belt",
    SKU: "DJ-AC-2572",
    Image:require('../Pages/Assets/Leather_Belt.jpg'),
    Department: "Fashion",
    Category: "Accessories",
    subcategory: "Belts",
    Brand: "Dein Accessories",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { M: 15, L: 20 } },
      { color: "Brown", sizes: { M: 10, L: 15 } }
    ],
    warehouseId: 2,
    aisle: "C1",
    row: "R2",
    shelf: "S5",
    bin: "B4",
    stock: 60,
    reserved: 10,
    available: 50,
    price: 999,
    currency: "INR",
    batchNumber: "B202607",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 2573,
    Name: "Baseball Cap",
    SKU: "DJ-AC-2573",
    Image:require('../Pages/Assets/Baseball_cap.jpg'),
    Department: "Fashion",
    Category: "Accessories",
    subcategory: "Hats & Caps",
    Brand: "Dein Accessories",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { OneSize: 50 } },
      { color: "Blue", sizes: { OneSize: 50 } }
    ],
    warehouseId: 1,
    aisle: "C2",
    row: "R1",
    shelf: "S2",
    bin: "B1",
    stock: 100,
    reserved: 20,
    available: 80,
    price: 499,
    currency: "INR",
    batchNumber: "B202608",
    serialNumbers: [],
    rating: 4.0,
  },
  {
    Id: 2574,
    Name: "Denim Top",
    Image:require('../Pages/Assets/Denim_top.jpg'),
    SKU: "DT-DT-2574",
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Top",
    Brand: "Dein Top",
    gender: "Female",
    variants: [
      { color: "White", sizes: { S: 30, M: 40, L: 30 } },
      { color: "Black", sizes: { S: 20, M: 30, L: 20 } }
    ],
    warehouseId: 3,
    aisle: "D1",
    row: "R3",
    shelf: "S1",
    bin: "B3",
    stock: 170,
    reserved: 50,
    available: 120,
    price: 799,
    currency: "INR",
    batchNumber: "B202609",
    serialNumbers: [],
    rating: 4.1,
  },
  {
    Id: 2575,
    Name: "Black Frock",
    Image:require('../Pages/Assets/Black_Frock.jpg'),
    SKU: "DJ-SW-2575",
    Department: "Fashion",
    Category: "Clothing",
    subcategory: "Dresses",
    Brand: "Dein Frok",
    gender: "Female",
    variants: [
      { color: "Red", sizes: { S: 10, M: 15, L: 10 } },
      { color: "Blue", sizes: { S: 5, M: 10, L: 5 } }
    ],
    warehouseId: 2,
    aisle: "E1",
    row: "R2",
    shelf: "S2",
    bin: "B2",
    stock: 55,
    reserved: 5,
    available: 50,
    price: 1499,
    currency: "INR",
    batchNumber: "B202610",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 3001,
    Name: "Smartphone X12",
    SKU: "EL-MB-3001",
    Image: require('../Pages/Assets/Smartphone_X12.jpg'),
    Department: "Electronics",
    Category: "Mobiles",
    subcategory: "Smartphones",
    Brand: "TechNova",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { "128GB": 20, "256GB": 15 } },
      { color: "Blue", sizes: { "128GB": 10, "256GB": 5 } }
    ],
    warehouseId: 1,
    aisle: "E1",
    row: "R1",
    shelf: "S2",
    bin: "B5",
    stock: 50,
    reserved: 10,
    available: 40,
    price: 69999,
    currency: "INR",
    batchNumber: "EL202601",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 3002,
    Name: "Wireless Bluetooth Headphones",
    SKU: "EL-AU-3002",
    Image: require('../Pages/Assets/Headphones.jpg'),
    Department: "Electronics",
    Category: "Audio",
    subcategory: "Headphones",
    Brand: "SoundMax",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { Standard: 30 } },
      { color: "White", sizes: { Standard: 20 } }
    ],
    warehouseId: 1,
    aisle: "E1",
    row: "R2",
    shelf: "S3",
    bin: "B7",
    stock: 50,
    reserved: 5,
    available: 45,
    price: 4999,
    currency: "INR",
    batchNumber: "EL202602",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 3003,
    Name: "4K Smart LED TV 55 Inch",
    SKU: "EL-TV-3003",
    Image: require('../Pages/Assets/Smart_TV.jpg'),
    Department: "Electronics",
    Category: "Television",
    subcategory: "Smart TV",
    Brand: "ViewPlus",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { "55inch": 12 } }
    ],
    warehouseId: 2,
    aisle: "E2",
    row: "R1",
    shelf: "S1",
    bin: "B2",
    stock: 12,
    reserved: 2,
    available: 10,
    price: 45999,
    currency: "INR",
    batchNumber: "EL202603",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 3004,
    Name: "Gaming Laptop Pro",
    SKU: "EL-LP-3004",
    Image: require('../Pages/Assets/Gaming_Laptop.jpg'),
    Department: "Electronics",
    Category: "Computers",
    subcategory: "Laptops",
    Brand: "GameCore",
    gender: "Unisex",
    variants: [
      { color: "Grey", sizes: { "16GB RAM": 8, "32GB RAM": 4 } }
    ],
    warehouseId: 2,
    aisle: "E2",
    row: "R3",
    shelf: "S4",
    bin: "B10",
    stock: 12,
    reserved: 3,
    available: 9,
    price: 119999,
    currency: "INR",
    batchNumber: "EL202604",
    serialNumbers: [],
    rating: 4.7,
  },
  {
    Id: 3005,
    Name: "Smartwatch Series 5",
    SKU: "EL-WR-3005",
    Image: require('../Pages/Assets/Smartwatch.jpg'),
    Department: "Electronics",
    Category: "Wearables",
    subcategory: "Smartwatch",
    Brand: "WristTech",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { Standard: 20 } },
      { color: "Silver", sizes: { Standard: 15 } }
    ],
    warehouseId: 1,
    aisle: "E3",
    row: "R1",
    shelf: "S2",
    bin: "B6",
    stock: 35,
    reserved: 5,
    available: 30,
    price: 14999,
    currency: "INR",
    batchNumber: "EL202605",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 3006,
    Name: "Bluetooth Portable Speaker",
    SKU: "EL-AU-3006",
    Image: require('../Pages/Assets/Speaker.jpg'),
    Department: "Electronics",
    Category: "Audio",
    subcategory: "Speakers",
    Brand: "BoomBox",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { Standard: 15 } },
      { color: "Black", sizes: { Standard: 25 } }
    ],
    warehouseId: 1,
    aisle: "E3",
    row: "R2",
    shelf: "S3",
    bin: "B9",
    stock: 40,
    reserved: 8,
    available: 32,
    price: 3499,
    currency: "INR",
    batchNumber: "EL202606",
    serialNumbers: [],
    rating: 4.1,
  },
  {
    Id: 3007,
    Name: "DSLR Camera 24MP",
    SKU: "EL-CM-3007",
    Image: require('../Pages/Assets/DSLR.jpg'),
    Department: "Electronics",
    Category: "Cameras",
    subcategory: "DSLR",
    Brand: "PhotoPro",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { BodyOnly: 6, "WithLens": 4 } }
    ],
    warehouseId: 2,
    aisle: "E4",
    row: "R1",
    shelf: "S1",
    bin: "B3",
    stock: 10,
    reserved: 2,
    available: 8,
    price: 54999,
    currency: "INR",
    batchNumber: "EL202607",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 3008,
    Name: "Wireless Keyboard & Mouse Combo",
    SKU: "EL-AC-3008",
    Image: require('../Pages/Assets/Keyboard_Mouse.jpg'),
    Department: "Electronics",
    Category: "Accessories",
    subcategory: "Computer Accessories",
    Brand: "KeyMate",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { Standard: 30 } }
    ],
    warehouseId: 1,
    aisle: "E4",
    row: "R2",
    shelf: "S4",
    bin: "B11",
    stock: 30,
    reserved: 5,
    available: 25,
    price: 1999,
    currency: "INR",
    batchNumber: "EL202608",
    serialNumbers: [],
    rating: 4.0,
  },
  {
    Id: 3009,
    Name: "WiFi Router Dual Band",
    SKU: "EL-NW-3009",
    Image: require('../Pages/Assets/Router.jpg'),
    Department: "Electronics",
    Category: "Networking",
    subcategory: "Routers",
    Brand: "NetLink",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { Standard: 18 } }
    ],
    warehouseId: 1,
    aisle: "E5",
    row: "R1",
    shelf: "S2",
    bin: "B4",
    stock: 18,
    reserved: 3,
    available: 15,
    price: 2999,
    currency: "INR",
    batchNumber: "EL202609",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 3010,
    Name: "Power Bank 20000mAh",
    SKU: "EL-AC-3010",
    Image: require('../Pages/Assets/Powerbank.jpg'),
    Department: "Electronics",
    Category: "Accessories",
    subcategory: "Power Banks",
    Brand: "ChargeIt",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { Standard: 40 } }
    ],
    warehouseId: 1,
    aisle: "E5",
    row: "R3",
    shelf: "S5",
    bin: "B14",
    stock: 40,
    reserved: 6,
    available: 34,
    price: 2499,
    currency: "INR",
    batchNumber: "EL202610",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 4001,
    Name: "Double Door Refrigerator 340L",
    SKU: "AP-RF-4001",
    Image: require('../Pages/Assets/Refrigerator.jpg'),
    Department: "Appliances",
    Category: "Kitchen Appliances",
    subcategory: "Refrigerator",
    Brand: "CoolFresh",
    gender: "Unisex",
    variants: [
      { color: "Silver", sizes: { "340L": 8 } },
      { color: "Black", sizes: { "340L": 6 } }
    ],
    warehouseId: 3,
    aisle: "A1",
    row: "R1",
    shelf: "S1",
    bin: "B1",
    stock: 14,
    reserved: 2,
    available: 12,
    price: 32999,
    currency: "INR",
    batchNumber: "AP202601",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 4002,
    Name: "Front Load Washing Machine 7kg",
    SKU: "AP-WM-4002",
    Image: require('../Pages/Assets/Washing_Machine.jpg'),
    Department: "Appliances",
    Category: "Laundry Appliances",
    subcategory: "Washing Machine",
    Brand: "WashPro",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { "7kg": 10 } }
    ],
    warehouseId: 3,
    aisle: "A1",
    row: "R2",
    shelf: "S2",
    bin: "B3",
    stock: 10,
    reserved: 1,
    available: 9,
    price: 27999,
    currency: "INR",
    batchNumber: "AP202602",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 4003,
    Name: "Split Air Conditioner 1.5 Ton",
    SKU: "AP-AC-4003",
    Image: require('../Pages/Assets/Air_Conditioner.jpg'),
    Department: "Appliances",
    Category: "Cooling Appliances",
    subcategory: "Air Conditioner",
    Brand: "AirFlow",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { "1.5Ton": 12 } }
    ],
    warehouseId: 3,
    aisle: "A2",
    row: "R1",
    shelf: "S3",
    bin: "B5",
    stock: 12,
    reserved: 3,
    available: 9,
    price: 40999,
    currency: "INR",
    batchNumber: "AP202603",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 4004,
    Name: "Microwave Oven 28L",
    SKU: "AP-MW-4004",
    Image: require('../Pages/Assets/Microwave.jpg'),
    Department: "Appliances",
    Category: "Kitchen Appliances",
    subcategory: "Microwave Oven",
    Brand: "HeatWave",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { "28L": 15 } }
    ],
    warehouseId: 3,
    aisle: "A2",
    row: "R2",
    shelf: "S4",
    bin: "B7",
    stock: 15,
    reserved: 2,
    available: 13,
    price: 18999,
    currency: "INR",
    batchNumber: "AP202604",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 4005,
    Name: "Mixer Grinder 750W",
    SKU: "AP-MG-4005",
    Image: require('../Pages/Assets/Mixer_Grinder.jpg'),
    Department: "Appliances",
    Category: "Kitchen Appliances",
    subcategory: "Mixer Grinder",
    Brand: "KitchenKing",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { "750W": 20 } }
    ],
    warehouseId: 3,
    aisle: "A3",
    row: "R1",
    shelf: "S1",
    bin: "B9",
    stock: 20,
    reserved: 4,
    available: 16,
    price: 3499,
    currency: "INR",
    batchNumber: "AP202605",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 4006,
    Name: "Induction Cooktop",
    SKU: "AP-IC-4006",
    Image: require('../Pages/Assets/Induction.jpg'),
    Department: "Appliances",
    Category: "Kitchen Appliances",
    subcategory: "Induction Cooktop",
    Brand: "CookSmart",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { Standard: 18 } }
    ],
    warehouseId: 3,
    aisle: "A3",
    row: "R2",
    shelf: "S2",
    bin: "B11",
    stock: 18,
    reserved: 3,
    available: 15,
    price: 2999,
    currency: "INR",
    batchNumber: "AP202606",
    serialNumbers: [],
    rating: 4.1,
  },
  {
    Id: 4007,
    Name: "Vacuum Cleaner 2000W",
    SKU: "AP-VC-4007",
    Image: require('../Pages/Assets/Vacuum_Cleaner.jpg'),
    Department: "Appliances",
    Category: "Home Appliances",
    subcategory: "Vacuum Cleaner",
    Brand: "CleanMax",
    gender: "Unisex",
    variants: [
      { color: "Blue", sizes: { "2000W": 10 } }
    ],
    warehouseId: 4,
    aisle: "A4",
    row: "R1",
    shelf: "S3",
    bin: "B13",
    stock: 10,
    reserved: 2,
    available: 8,
    price: 8999,
    currency: "INR",
    batchNumber: "AP202607",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 4008,
    Name: "Electric Water Heater 25L",
    SKU: "AP-WH-4008",
    Image: require('../Pages/Assets/Water_Heater.jpg'),
    Department: "Appliances",
    Category: "Bathroom Appliances",
    subcategory: "Water Heater",
    Brand: "HeatSafe",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { "25L": 14 } }
    ],
    warehouseId: 4,
    aisle: "A4",
    row: "R2",
    shelf: "S4",
    bin: "B15",
    stock: 14,
    reserved: 2,
    available: 12,
    price: 10999,
    currency: "INR",
    batchNumber: "AP202608",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 4009,
    Name: "Room Air Cooler",
    SKU: "AP-CL-4009",
    Image: require('../Pages/Assets/Air_Cooler.jpg'),
    Department: "Appliances",
    Category: "Cooling Appliances",
    subcategory: "Air Cooler",
    Brand: "BreezeCool",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { Standard: 16 } }
    ],
    warehouseId: 4,
    aisle: "A5",
    row: "R1",
    shelf: "S1",
    bin: "B2",
    stock: 16,
    reserved: 3,
    available: 13,
    price: 7999,
    currency: "INR",
    batchNumber: "AP202609",
    serialNumbers: [],
    rating: 4.0,
  },
  {
    Id: 4010,
    Name: "Dishwasher 12 Place Settings",
    SKU: "AP-DW-4010",
    Image: require('../Pages/Assets/Dishwasher.jpg'),
    Department: "Appliances",
    Category: "Kitchen Appliances",
    subcategory: "Dishwasher",
    Brand: "WashEase",
    gender: "Unisex",
    variants: [
      { color: "Silver", sizes: { "12Place": 6 } }
    ],
    warehouseId: 4,
    aisle: "A5",
    row: "R2",
    shelf: "S2",
    bin: "B4",
    stock: 6,
    reserved: 1,
    available: 5,
    price: 35999,
    currency: "INR",
    batchNumber: "AP202610",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 5001,
    Name: "Hydrating Face Cream",
    SKU: "BT-SK-5001",
    Image: require('../Pages/Assets/Face_Cream.jpg'),
    Department: "Beauty",
    Category: "Skincare",
    subcategory: "Moisturizer",
    Brand: "GlowCare",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "50ml": 25, "100ml": 15 } }
    ],
    warehouseId: 5,
    aisle: "B1",
    row: "R1",
    shelf: "S1",
    bin: "B1",
    stock: 40,
    reserved: 6,
    available: 34,
    price: 899,
    currency: "INR",
    batchNumber: "BT202601",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 5002,
    Name: "Vitamin C Face Serum",
    SKU: "BT-SK-5002",
    Image: require('../Pages/Assets/Face_Serum.jpg'),
    Department: "Beauty",
    Category: "Skincare",
    subcategory: "Serum",
    Brand: "PureSkin",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "30ml": 30 } }
    ],
    warehouseId: 5,
    aisle: "B1",
    row: "R2",
    shelf: "S2",
    bin: "B3",
    stock: 30,
    reserved: 5,
    available: 25,
    price: 1199,
    currency: "INR",
    batchNumber: "BT202602",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 5003,
    Name: "Matte Finish Foundation",
    SKU: "BT-MK-5003",
    Image: require('../Pages/Assets/Foundation.jpg'),
    Department: "Beauty",
    Category: "Makeup",
    subcategory: "Foundation",
    Brand: "FacePerfect",
    gender: "Female",
    variants: [
      { color: "Beige", sizes: { "30ml": 12 } },
      { color: "Natural", sizes: { "30ml": 10 } }
    ],
    warehouseId: 5,
    aisle: "B2",
    row: "R1",
    shelf: "S3",
    bin: "B5",
    stock: 22,
    reserved: 4,
    available: 18,
    price: 1499,
    currency: "INR",
    batchNumber: "BT202603",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 5004,
    Name: "Waterproof Mascara",
    SKU: "BT-MK-5004",
    Image: require('../Pages/Assets/Mascara.jpg'),
    Department: "Beauty",
    Category: "Makeup",
    subcategory: "Mascara",
    Brand: "LashUp",
    gender: "Female",
    variants: [
      { color: "Black", sizes: { Standard: 35 } }
    ],
    warehouseId: 5,
    aisle: "B2",
    row: "R2",
    shelf: "S4",
    bin: "B7",
    stock: 35,
    reserved: 6,
    available: 29,
    price: 699,
    currency: "INR",
    batchNumber: "BT202604",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 5005,
    Name: "Herbal Shampoo",
    SKU: "BT-HC-5005",
    Image: require('../Pages/Assets/Shampoo.jpg'),
    Department: "Beauty",
    Category: "Hair Care",
    subcategory: "Shampoo",
    Brand: "HerbGlow",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "250ml": 20, "500ml": 15 } }
    ],
    warehouseId: 5,
    aisle: "B3",
    row: "R1",
    shelf: "S1",
    bin: "B9",
    stock: 35,
    reserved: 5,
    available: 30,
    price: 499,
    currency: "INR",
    batchNumber: "BT202605",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 5006,
    Name: "Hair Conditioner",
    SKU: "BT-HC-5006",
    Image: require('../Pages/Assets/Conditioner.jpg'),
    Department: "Beauty",
    Category: "Hair Care",
    subcategory: "Conditioner",
    Brand: "SilkStrand",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "250ml": 18 } }
    ],
    warehouseId: 5,
    aisle: "B3",
    row: "R2",
    shelf: "S2",
    bin: "B11",
    stock: 18,
    reserved: 3,
    available: 15,
    price: 549,
    currency: "INR",
    batchNumber: "BT202606",
    serialNumbers: [],
    rating: 4.1,
  },
  {
    Id: 5007,
    Name: "Luxury Perfume",
    SKU: "BT-FR-5007",
    Image: require('../Pages/Assets/Perfume.jpg'),
    Department: "Beauty",
    Category: "Fragrance",
    subcategory: "Perfume",
    Brand: "AromaLux",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "50ml": 10, "100ml": 8 } }
    ],
    warehouseId: 6,
    aisle: "B4",
    row: "R1",
    shelf: "S3",
    bin: "B13",
    stock: 18,
    reserved: 4,
    available: 14,
    price: 3999,
    currency: "INR",
    batchNumber: "BT202607",
    serialNumbers: [],
    rating: 4.7,
  },
  {
    Id: 5008,
    Name: "Sunscreen SPF 50",
    SKU: "BT-SK-5008",
    Image: require('../Pages/Assets/Sunscreen.jpg'),
    Department: "Beauty",
    Category: "Skincare",
    subcategory: "Sunscreen",
    Brand: "SunShield",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "50ml": 28 } }
    ],
    warehouseId: 6,
    aisle: "B4",
    row: "R2",
    shelf: "S4",
    bin: "B15",
    stock: 28,
    reserved: 4,
    available: 24,
    price: 799,
    currency: "INR",
    batchNumber: "BT202608",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 5009,
    Name: "Nail Polish Set",
    SKU: "BT-MK-5009",
    Image: require('../Pages/Assets/Nail_Polish.jpg'),
    Department: "Beauty",
    Category: "Makeup",
    subcategory: "Nail Care",
    Brand: "ColorPop",
    gender: "Female",
    variants: [
      { color: "Multi", sizes: { SetOf6: 20 } }
    ],
    warehouseId: 6,
    aisle: "B5",
    row: "R1",
    shelf: "S1",
    bin: "B2",
    stock: 20,
    reserved: 3,
    available: 17,
    price: 999,
    currency: "INR",
    batchNumber: "BT202609",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 5010,
    Name: "Facial Cleanser",
    SKU: "BT-SK-5010",
    Image: require('../Pages/Assets/Face_Cleanser.jpg'),
    Department: "Beauty",
    Category: "Skincare",
    subcategory: "Cleanser",
    Brand: "FreshSkin",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { "100ml": 24 } }
    ],
    warehouseId: 6,
    aisle: "B5",
    row: "R2",
    shelf: "S2",
    bin: "B4",
    stock: 24,
    reserved: 4,
    available: 20,
    price: 649,
    currency: "INR",
    batchNumber: "BT202610",
    serialNumbers: [],
    rating: 4.4,
  },{
    Id: 6001,
    Name: "Remote Control Car",
    SKU: "TY-VH-6001",
    Image: require('../Pages/Assets/RC_Car.jpg'),
    Department: "Toys",
    Category: "Vehicles",
    subcategory: "RC Cars",
    Brand: "SpeedRacer",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { Standard: 12 } },
      { color: "Blue", sizes: { Standard: 8 } }
    ],
    warehouseId: 7,
    aisle: "T1",
    row: "R1",
    shelf: "S1",
    bin: "B1",
    stock: 20,
    reserved: 3,
    available: 17,
    price: 1999,
    currency: "INR",
    batchNumber: "TY202601",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 6002,
    Name: "Building Blocks Set",
    SKU: "TY-ED-6002",
    Image: require('../Pages/Assets/Building_Blocks.jpg'),
    Department: "Toys",
    Category: "Educational Toys",
    subcategory: "Blocks",
    Brand: "BrainBuild",
    gender: "Unisex",
    variants: [
      { color: "Multi", sizes: { "500pcs": 15 } }
    ],
    warehouseId: 7,
    aisle: "T1",
    row: "R2",
    shelf: "S2",
    bin: "B3",
    stock: 15,
    reserved: 2,
    available: 13,
    price: 1499,
    currency: "INR",
    batchNumber: "TY202602",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 6003,
    Name: "Stuffed Teddy Bear",
    SKU: "TY-PL-6003",
    Image: require('../Pages/Assets/Teddy_Bear.jpg'),
    Department: "Toys",
    Category: "Soft Toys",
    subcategory: "Stuffed Animals",
    Brand: "CuddleSoft",
    gender: "Unisex",
    variants: [
      { color: "Brown", sizes: { "Medium": 20 } }
    ],
    warehouseId: 7,
    aisle: "T2",
    row: "R1",
    shelf: "S1",
    bin: "B5",
    stock: 20,
    reserved: 4,
    available: 16,
    price: 899,
    currency: "INR",
    batchNumber: "TY202603",
    serialNumbers: [],
    rating: 4.7,
  },
  {
    Id: 6004,
    Name: "Kids Learning Tablet",
    SKU: "TY-EL-6004",
    Image: require('../Pages/Assets/Kids_Tablet.jpg'),
    Department: "Toys",
    Category: "Electronic Toys",
    subcategory: "Learning Devices",
    Brand: "EduPlay",
    gender: "Unisex",
    variants: [
      { color: "Green", sizes: { Standard: 10 } }
    ],
    warehouseId: 7,
    aisle: "T2",
    row: "R2",
    shelf: "S3",
    bin: "B7",
    stock: 10,
    reserved: 2,
    available: 8,
    price: 3499,
    currency: "INR",
    batchNumber: "TY202604",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 6005,
    Name: "Puzzle Game 1000 Pieces",
    SKU: "TY-GM-6005",
    Image: require('../Pages/Assets/Puzzle.jpg'),
    Department: "Toys",
    Category: "Games",
    subcategory: "Puzzles",
    Brand: "MindQuest",
    gender: "Unisex",
    variants: [
      { color: "Multi", sizes: { "1000pcs": 14 } }
    ],
    warehouseId: 7,
    aisle: "T3",
    row: "R1",
    shelf: "S2",
    bin: "B9",
    stock: 14,
    reserved: 3,
    available: 11,
    price: 1299,
    currency: "INR",
    batchNumber: "TY202605",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 6006,
    Name: "Action Figure Superhero",
    SKU: "TY-FG-6006",
    Image: require('../Pages/Assets/Action_Figure.jpg'),
    Department: "Toys",
    Category: "Figures",
    subcategory: "Action Figures",
    Brand: "HeroFlex",
    gender: "Male",
    variants: [
      { color: "Multi", sizes: { Standard: 18 } }
    ],
    warehouseId: 8,
    aisle: "T3",
    row: "R2",
    shelf: "S4",
    bin: "B11",
    stock: 18,
    reserved: 4,
    available: 14,
    price: 1099,
    currency: "INR",
    batchNumber: "TY202606",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 6007,
    Name: "Doll House Play Set",
    SKU: "TY-DL-6007",
    Image: require('../Pages/Assets/Doll_House.jpg'),
    Department: "Toys",
    Category: "Dolls",
    subcategory: "Play Sets",
    Brand: "DreamHome",
    gender: "Female",
    variants: [
      { color: "Pink", sizes: { Large: 6 } }
    ],
    warehouseId: 8,
    aisle: "T4",
    row: "R1",
    shelf: "S1",
    bin: "B2",
    stock: 6,
    reserved: 1,
    available: 5,
    price: 4999,
    currency: "INR",
    batchNumber: "TY202607",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 6008,
    Name: "Kids Cricket Bat Set",
    SKU: "TY-SP-6008",
    Image: require('../Pages/Assets/Kids_Cricket.jpg'),
    Department: "Toys",
    Category: "Sports Toys",
    subcategory: "Cricket",
    Brand: "PlaySport",
    gender: "Unisex",
    variants: [
      { color: "Wood", sizes: { Junior: 16 } }
    ],
    warehouseId: 8,
    aisle: "T4",
    row: "R2",
    shelf: "S2",
    bin: "B4",
    stock: 16,
    reserved: 3,
    available: 13,
    price: 799,
    currency: "INR",
    batchNumber: "TY202608",
    serialNumbers: [],
    rating: 4.1,
  },
  {
    Id: 6009,
    Name: "Ride-On Toy Car",
    SKU: "TY-RD-6009",
    Image: require('../Pages/Assets/Ride_On_Car.jpg'),
    Department: "Toys",
    Category: "Ride Ons",
    subcategory: "Kids Vehicles",
    Brand: "TinyWheels",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { Standard: 5 } }
    ],
    warehouseId: 8,
    aisle: "T5",
    row: "R1",
    shelf: "S3",
    bin: "B6",
    stock: 5,
    reserved: 1,
    available: 4,
    price: 5999,
    currency: "INR",
    batchNumber: "TY202609",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 6010,
    Name: "Art & Craft Kit",
    SKU: "TY-CR-6010",
    Image: require('../Pages/Assets/Art_Craft.jpg'),
    Department: "Toys",
    Category: "Creative Toys",
    subcategory: "Art & Craft",
    Brand: "CraftyKids",
    gender: "Unisex",
    variants: [
      { color: "Multi", sizes: { Standard: 22 } }
    ],
    warehouseId: 8,
    aisle: "T5",
    row: "R2",
    shelf: "S4",
    bin: "B8",
    stock: 22,
    reserved: 4,
    available: 18,
    price: 999,
    currency: "INR",
    batchNumber: "TY202610",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 7001,
    Name: "Cricket Bat English Willow",
    SKU: "SP-CR-7001",
    Image: require('../Pages/Assets/Cricket_Bat.jpg'),
    Department: "Sports",
    Category: "Cricket",
    subcategory: "Bats",
    Brand: "ProStrike",
    gender: "Unisex",
    variants: [
      { color: "Wood", sizes: { ShortHandle: 10, LongHandle: 6 } }
    ],
    warehouseId: 9,
    aisle: "S1",
    row: "R1",
    shelf: "S1",
    bin: "B1",
    stock: 16,
    reserved: 3,
    available: 13,
    price: 5499,
    currency: "INR",
    batchNumber: "SP202601",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 7002,
    Name: "Cricket Leather Ball",
    SKU: "SP-CR-7002",
    Image: require('../Pages/Assets/Cricket_Ball.jpg'),
    Department: "Sports",
    Category: "Cricket",
    subcategory: "Balls",
    Brand: "SwingMaster",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { Standard: 30 } }
    ],
    warehouseId: 9,
    aisle: "S1",
    row: "R2",
    shelf: "S2",
    bin: "B3",
    stock: 30,
    reserved: 5,
    available: 25,
    price: 399,
    currency: "INR",
    batchNumber: "SP202602",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 7003,
    Name: "Football Size 5",
    SKU: "SP-FB-7003",
    Image: require('../Pages/Assets/Football.jpg'),
    Department: "Sports",
    Category: "Football",
    subcategory: "Balls",
    Brand: "GoalPro",
    gender: "Unisex",
    variants: [
      { color: "White", sizes: { Size5: 25 } }
    ],
    warehouseId: 9,
    aisle: "S2",
    row: "R1",
    shelf: "S3",
    bin: "B5",
    stock: 25,
    reserved: 4,
    available: 21,
    price: 1299,
    currency: "INR",
    batchNumber: "SP202603",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 7004,
    Name: "Badminton Racket Set",
    SKU: "SP-BD-7004",
    Image: require('../Pages/Assets/Badminton_Racket.jpg'),
    Department: "Sports",
    Category: "Badminton",
    subcategory: "Rackets",
    Brand: "SmashX",
    gender: "Unisex",
    variants: [
      { color: "Blue", sizes: { Standard: 12 } }
    ],
    warehouseId: 9,
    aisle: "S2",
    row: "R2",
    shelf: "S4",
    bin: "B7",
    stock: 12,
    reserved: 2,
    available: 10,
    price: 2499,
    currency: "INR",
    batchNumber: "SP202604",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 7005,
    Name: "Yoga Mat Anti-Slip",
    SKU: "SP-YG-7005",
    Image: require('../Pages/Assets/Yoga_Mat.jpg'),
    Department: "Sports",
    Category: "Fitness",
    subcategory: "Yoga Mats",
    Brand: "ZenFit",
    gender: "Unisex",
    variants: [
      { color: "Purple", sizes: { Standard: 40 } },
      { color: "Green", sizes: { Standard: 25 } }
    ],
    warehouseId: 10,
    aisle: "S3",
    row: "R1",
    shelf: "S1",
    bin: "B9",
    stock: 65,
    reserved: 10,
    available: 55,
    price: 999,
    currency: "INR",
    batchNumber: "SP202605",
    serialNumbers: [],
    rating: 4.7,
  },
  {
    Id: 7006,
    Name: "Dumbbell Set 20kg",
    SKU: "SP-GM-7006",
    Image: require('../Pages/Assets/Dumbbell_Set.jpg'),
    Department: "Sports",
    Category: "Gym Equipment",
    subcategory: "Dumbbells",
    Brand: "IronFlex",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { "20kg": 14 } }
    ],
    warehouseId: 10,
    aisle: "S3",
    row: "R2",
    shelf: "S2",
    bin: "B11",
    stock: 14,
    reserved: 3,
    available: 11,
    price: 3999,
    currency: "INR",
    batchNumber: "SP202606",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 7007,
    Name: "Running Shoes",
    SKU: "SP-RN-7007",
    Image: require('../Pages/Assets/Running_Shoes.jpg'),
    Department: "Sports",
    Category: "Footwear",
    subcategory: "Running Shoes",
    Brand: "RunFast",
    gender: "Unisex",
    variants: [
      { color: "Black", sizes: { "7": 6, "8": 8, "9": 10 } },
      { color: "Blue", sizes: { "8": 5, "9": 7 } }
    ],
    warehouseId: 10,
    aisle: "S4",
    row: "R1",
    shelf: "S3",
    bin: "B13",
    stock: 36,
    reserved: 6,
    available: 30,
    price: 4999,
    currency: "INR",
    batchNumber: "SP202607",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 7008,
    Name: "Cycling Helmet",
    SKU: "SP-CY-7008",
    Image: require('../Pages/Assets/Cycling_Helmet.jpg'),
    Department: "Sports",
    Category: "Cycling",
    subcategory: "Helmets",
    Brand: "SafeRide",
    gender: "Unisex",
    variants: [
      { color: "Red", sizes: { Medium: 10, Large: 8 } }
    ],
    warehouseId: 10,
    aisle: "S4",
    row: "R2",
    shelf: "S4",
    bin: "B15",
    stock: 18,
    reserved: 3,
    available: 15,
    price: 1799,
    currency: "INR",
    batchNumber: "SP202608",
    serialNumbers: [],
    rating: 4.4,
  },
  {
    Id: 7009,
    Name: "Tennis Racket",
    SKU: "SP-TN-7009",
    Image: require('../Pages/Assets/Tennis_Racket.jpg'),
    Department: "Sports",
    Category: "Tennis",
    subcategory: "Rackets",
    Brand: "AcePro",
    gender: "Unisex",
    variants: [
      { color: "Green", sizes: { Standard: 12 } }
    ],
    warehouseId: 11,
    aisle: "S5",
    row: "R1",
    shelf: "S1",
    bin: "B2",
    stock: 12,
    reserved: 2,
    available: 10,
    price: 2999,
    currency: "INR",
    batchNumber: "SP202609",
    serialNumbers: [],
    rating: 4.3,
  },
  {
    Id: 7010,
    Name: "Swimming Goggles",
    SKU: "SP-SW-7010",
    Image: require('../Pages/Assets/Swimming_Goggles.jpg'),
    Department: "Sports",
    Category: "Swimming",
    subcategory: "Goggles",
    Brand: "AquaView",
    gender: "Unisex",
    variants: [
      { color: "Blue", sizes: { Standard: 28 } }
    ],
    warehouseId: 11,
    aisle: "S5",
    row: "R2",
    shelf: "S2",
    bin: "B4",
    stock: 28,
    reserved: 5,
    available: 23,
    price: 699,
    currency: "INR",
    batchNumber: "SP202610",
    serialNumbers: [],
    rating: 4.2,
  },
  {
    Id: 8001,
    Name: "The Great Gatsby",
    SKU: "BK-FC-8001",
    Image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
    Department: "Books",
    Category: "Fiction",
    subcategory: "Classic",
    Brand: "Scribner",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 15, Paperback: 20 } }
    ],
    warehouseId: 12,
    aisle: "B1",
    row: "R1",
    shelf: "S1",
    bin: "B1",
    stock: 35,
    reserved: 5,
    available: 30,
    price: 599,
    currency: "INR",
    batchNumber: "BK202601",
    serialNumbers: [],
    rating: 4.8,
  },
  {
    Id: 8002,
    Name: "Atomic Habits",
    SKU: "BK-NF-8002",
    Image: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    Department: "Books",
    Category: "Non-Fiction",
    subcategory: "Self Help",
    Brand: "Penguin",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 10, Paperback: 15 } }
    ],
    warehouseId: 12,
    aisle: "B1",
    row: "R2",
    shelf: "S2",
    bin: "B3",
    stock: 25,
    reserved: 3,
    available: 22,
    price: 499,
    currency: "INR",
    batchNumber: "BK202602",
    serialNumbers: [],
    rating: 4.7,
  },
  {
    Id: 8003,
    Name: "Harry Potter and the Sorcerer's Stone",
    SKU: "BK-FC-8003",
    Image: "https://images.unsplash.com/photo-1588776814546-3f1c6b873a4f",
    Department: "Books",
    Category: "Fiction",
    subcategory: "Fantasy",
    Brand: "Bloomsbury",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 12, Paperback: 20 } }
    ],
    warehouseId: 12,
    aisle: "B2",
    row: "R1",
    shelf: "S3",
    bin: "B5",
    stock: 32,
    reserved: 5,
    available: 27,
    price: 799,
    currency: "INR",
    batchNumber: "BK202603",
    serialNumbers: [],
    rating: 4.9,
  },
  {
    Id: 8004,
    Name: "Educated",
    SKU: "BK-NF-8004",
    Image: "https://images.unsplash.com/photo-1532012197267-da84d127e765",
    Department: "Books",
    Category: "Non-Fiction",
    subcategory: "Memoir",
    Brand: "Random House",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 8, Paperback: 12 } }
    ],
    warehouseId: 12,
    aisle: "B2",
    row: "R2",
    shelf: "S4",
    bin: "B7",
    stock: 20,
    reserved: 2,
    available: 18,
    price: 699,
    currency: "INR",
    batchNumber: "BK202604",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 8005,
    Name: "The Alchemist",
    SKU: "BK-FC-8005",
    Image: "https://images.unsplash.com/photo-1532012197266-9e4a1ef2dbb3",
    Department: "Books",
    Category: "Fiction",
    subcategory: "Adventure",
    Brand: "HarperCollins",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Paperback: 25 } }
    ],
    warehouseId: 13,
    aisle: "B3",
    row: "R1",
    shelf: "S1",
    bin: "B9",
    stock: 25,
    reserved: 4,
    available: 21,
    price: 399,
    currency: "INR",
    batchNumber: "BK202605",
    serialNumbers: [],
    rating: 4.7,
  },
  {
    Id: 8006,
    Name: "Sapiens: A Brief History of Humankind",
    SKU: "BK-NF-8006",
    Image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    Department: "Books",
    Category: "Non-Fiction",
    subcategory: "History",
    Brand: "Harper",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 10, Paperback: 15 } }
    ],
    warehouseId: 13,
    aisle: "B3",
    row: "R2",
    shelf: "S2",
    bin: "B11",
    stock: 25,
    reserved: 3,
    available: 22,
    price: 899,
    currency: "INR",
    batchNumber: "BK202606",
    serialNumbers: [],
    rating: 4.8,
  },
  {
    Id: 8007,
    Name: "The Catcher in the Rye",
    SKU: "BK-FC-8007",
    Image: "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4",
    Department: "Books",
    Category: "Fiction",
    subcategory: "Classic",
    Brand: "Little, Brown",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Paperback: 18 } }
    ],
    warehouseId: 13,
    aisle: "B4",
    row: "R1",
    shelf: "S3",
    bin: "B13",
    stock: 18,
    reserved: 2,
    available: 16,
    price: 499,
    currency: "INR",
    batchNumber: "BK202607",
    serialNumbers: [],
    rating: 4.5,
  },
  {
    Id: 8008,
    Name: "To Kill a Mockingbird",
    SKU: "BK-FC-8008",
    Image: "https://images.unsplash.com/photo-1523475496153-3f62d6fda1b6",
    Department: "Books",
    Category: "Fiction",
    subcategory: "Classic",
    Brand: "J.B. Lippincott & Co.",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 12, Paperback: 20 } }
    ],
    warehouseId: 13,
    aisle: "B4",
    row: "R2",
    shelf: "S4",
    bin: "B15",
    stock: 32,
    reserved: 4,
    available: 28,
    price: 699,
    currency: "INR",
    batchNumber: "BK202608",
    serialNumbers: [],
    rating: 4.9,
  },
  {
    Id: 8009,
    Name: "Thinking, Fast and Slow",
    SKU: "BK-NF-8009",
    Image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66",
    Department: "Books",
    Category: "Non-Fiction",
    subcategory: "Psychology",
    Brand: "Farrar, Straus and Giroux",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 10, Paperback: 15 } }
    ],
    warehouseId: 14,
    aisle: "B5",
    row: "R1",
    shelf: "S1",
    bin: "B2",
    stock: 25,
    reserved: 3,
    available: 22,
    price: 899,
    currency: "INR",
    batchNumber: "BK202609",
    serialNumbers: [],
    rating: 4.6,
  },
  {
    Id: 8010,
    Name: "The Subtle Art of Not Giving a F*ck",
    SKU: "BK-NF-8010",
    Image: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d",
    Department: "Books",
    Category: "Non-Fiction",
    subcategory: "Self Help",
    Brand: "HarperOne",
    gender: "Unisex",
    variants: [
      { color: "N/A", sizes: { Hardcover: 12, Paperback: 18 } }
    ],
    warehouseId: 14,
    aisle: "B5",
    row: "R2",
    shelf: "S2",
    bin: "B4",
    stock: 30,
    reserved: 5,
    available: 25,
    price: 699,
    currency: "INR",
    batchNumber: "BK202610",
    serialNumbers: [],
    rating: 4.7,
  }
];
const warehouse=[...new Set(InventoryData.map(i=>i.warehouseId.toString()))]
export {InventoryData,warehouse};
