const dayAgo = (days) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
};

const Ordersdata = [
  {
    Id: 2566,
    Image:require('../Assets/Dein_Jeans.jpg'),
    Name: 'Dein Jeans',
    company: 'Dein Apparel',
    sku: 'DJ-CL-2566',
    Department: 'Fashion',
    category: 'Clothing',
    gender:'Male',
    sizes:{'S':10,'M':20,'L':30,'XL':25,'2XL':15},
    description: 'Slim-fit denim jeans made from premium cotton fabric.',
    warehouse: 2,
    stock: 100,
    price: 1500,
    currency: 'INR',
    discount: 10,
    rating: 4.2,
    supplier: 'Dein Clothing Pvt Ltd',
    ordered_Date: dayAgo(0),
    status: 'Pending',
    charges:5000,
    gst:10,
  },

  {
    Id: 2567,
    Name: 'Nike Shoes',
    Image:require('../Assets/Nike_Shoes.jpg'),
    company: 'Nike',
    sku: 'NK-FW-2567',
    Department: 'Fashion',
    category: 'Footwear',
    gender:'Male',
    sizes:{7:15,8:20,9:5,10:5,11:5},
    description: 'Lightweight running shoes with breathable mesh design.',
    warehouse: 1,
    stock: 50,
    price: 3200,
    currency: 'INR',
    discount: 5,
    rating: 4.6,
    supplier: 'Nike India',
    ordered_Date: dayAgo(1),
    status: 'Delivered',
    charges:2000,
    gst:7,
  },

  {
    Id: 2568,
    Name: 'Apple Watch',
    Image:require('../Assets/Apple_Watch.jpg'),
    company: 'Apple',
    sku: 'APL-WR-2568',
    Department: 'Electronics',
    category: 'Wearables',
    description: 'Smartwatch with fitness tracking, heart-rate monitoring, and GPS.',
    warehouse: 3,
    stock: 30,
    price: 28000,
    currency: 'INR',
    discount: 0,
    rating: 4.8,
    supplier: 'Apple Authorized Distributor',
    ordered_Date: dayAgo(2),
    status: 'Shipped',
    charges:1000,
    gst:10,
  },

  {
    Id: 2569,
    Name: 'Office Chair',
    Image:require('../Assets/Office_chair.jpg'),
    company: 'Godrej Interio',
    sku: 'GDJ-FN-2569',
    Department: 'Furniture',
    category: 'Seating',
    description: 'Ergonomic office chair with adjustable height and lumbar support.',
    warehouse: 1,
    stock: 20,
    price: 7500,
    currency: 'INR',
    discount: 12,
    rating: 4.1,
    supplier: 'Godrej Furniture',
    ordered_Date: dayAgo(3),
    status: 'Pending',
    charges:2000,
    gst:7,
  },

  {
    Id: 2570,
    Name: 'Samsung TV',
    Image:require('../Assets/Samsung TV.jpg'),
    company: 'Samsung',
    sku: 'SMS-TV-2570',
    Department: 'Electronics',
    category: 'Television',
    description: '55-inch Smart LED TV with 4K UHD resolution.',
    warehouse: 2,
    stock: 15,
    price: 42000,
    currency: 'INR',
    discount: 15,
    rating: 4.7,
    supplier: 'Samsung India Electronics',
    ordered_Date: dayAgo(4),
    status: 'Delivered',
    charges:2000,
    gst:7,
  },

  {
    Id: 2571,
    Name: 'Puma T-Shirt',
    Image:require('../Assets/Puma_Tshirt.jpg'),
    company: 'Puma',
    sku: 'PMA-CL-2571',
    Department: 'Fashion',
    category: 'Clothing',
    gender:'Unisex',
    sizes:{'S':30,'M':50,'L':50,'XL':50,'2XL':20},
    description: 'Comfortable cotton t-shirt suitable for casual wear.',
    warehouse: 1,
    stock: 200,
    price: 1200,
    currency: 'INR',
    discount: 20,
    rating: 4.3,
    supplier: 'Puma Sports India',
    ordered_Date: dayAgo(5),
    status: 'Cancelled',
    charges:2000,
    gst:5,
  },

  {
    Id: 2572,
    Name: 'Wooden Table',
    Image:require('../Assets/Wooden_Table.jpg'),
    company: 'IKEA',
    sku: 'IK-FN-2572',
    Department: 'Furniture',
    category: 'Tables',
    description: 'Solid wooden dining table with polished finish.',
    warehouse: 3,
    stock: 10,
    price: 9800,
    currency: 'INR',
    discount: 8,
    rating: 4.0,
    supplier: 'IKEA India',
    ordered_Date: dayAgo(6),
    status: 'Pending',
    charges:2000,
    gst:7,
  },

  {
    Id: 2573,
    Name: 'HP Laptop',
    Image:require('../Assets/HP_Laptop.jpg'),
    company: 'HP',
    sku: 'HP-CM-2573',
    Department: 'Electronics',
    category: 'Computers',
    description: '15.6-inch laptop with Intel i5 processor and SSD storage.',
    warehouse: 4,
    stock: 25,
    price: 58000,
    currency: 'INR',
    discount: 10,
    rating: 4.5,
    supplier: 'HP India Sales',
    ordered_Date: dayAgo(7),
    status: 'Shipped',
    charges:2000,
    gst:7,

  },

  {
    Id: 2574,
    Name: 'Adidas Cap',
    Image:require('../Assets/Adidas_cap.jpg'),
    company: 'Adidas',
    sku: 'ADS-AC-2574',
    Department: 'Fashion',
    category: 'Accessories',
    description: 'Sports cap with adjustable strap and breathable fabric.',
    warehouse: 2,
    stock: 150,
    price: 900,
    currency: 'INR',
    discount: 5,
    rating: 4.4,
    supplier: 'Adidas India',
    ordered_Date: dayAgo(8),
    status: 'Delivered',
    charges:2000,
    gst:3,
  },

  {
    Id: 2575,
    Name: 'JBL Bluetooth Speaker',
    Image:require('../Assets/JBL_bluetooth.jpg'),
    company: 'JBL',
    sku: 'JBL-AU-2575',
    Department: 'Electronics',
    category: 'Audio',
    description: 'Portable Bluetooth speaker with deep bass and waterproof design.',
    warehouse: 1,
    stock: 60,
    price: 4500,
    currency: 'INR',
    discount: 18,
    rating: 4.6,
    supplier: 'Harman Audio',
    ordered_Date: dayAgo(8),
    status: 'Pending',
    charges:2000,
    gst:8,
  },
  {
  Id: 2576,
  Name: 'Reebok Shorts',
  Image:require('../Assets/Reebok_Shorts.jpg'),
  company: 'Reebok',
  sku: 'RBK-CL-2576',
  Department: 'Fashion',
  category: 'Clothing',
  gender:'Unisex',
  size:{'S':20,'M':30,'L':30,'XL':10},
  description: 'Breathable sports shorts designed for training and workouts.',
  warehouse: 3,
  stock: 90,
  price: 1100,
  currency: 'INR',
  discount: 10,
  rating: 4.2,
  supplier: 'Reebok India',
  ordered_Date: dayAgo(8),
  status: 'Delivered',
  charges:3000,
  gst:7,
},
{
  Id: 2577,
  Name: 'Study Lamp',
  Image:require('../Assets/Study_Lamp.jpg'),
  company: 'Philips',
  sku: 'PHL-LT-2577',
  Department: 'Home Decor',
  category: 'Lighting',
  description: 'LED study lamp with adjustable neck and eye-protection mode.',
  warehouse: 2,
  stock: 70,
  price: 1800,
  currency: 'INR',
  discount: 12,
  rating: 4.4,
  supplier: 'Philips Lighting India',
  ordered_Date: dayAgo(9),
  status: 'Shipped',
  charges:3000,
  gst:7,
},
{
  Id: 2578,
  Name: 'Microwave Oven',
  Image:require('../Assets/Microwave.jpg'),
  company: 'LG',
  sku: 'LG-KT-2578',
  Department: 'Appliances',
  category: 'Kitchen',
  description: '20L convection microwave oven with multiple auto-cook menus.',
  warehouse: 3,
  stock: 18,
  price: 12500,
  currency: 'INR',
  discount: 15,
  rating: 4.5,
  supplier: 'LG Electronics India',
  ordered_Date: dayAgo(9),
  status: 'Pending',
  charges:4000,
  gst:9,
},
{
  Id: 2579,
  Name: 'Leather Wallet',
  Image:require('../Assets/Leather Wallet.jpg'),
  company: 'Wildcraft',
  sku: 'WLD-AC-2579',
  Department: 'Fashion',
  category: 'Accessories',
  description: 'Genuine leather wallet with multiple card slots.',
  warehouse: 1,
  stock: 140,
  price: 1600,
  currency: 'INR',
  discount: 8,
  rating: 4.3,
  supplier: 'Wildcraft India',
  ordered_Date: dayAgo(10),
  status: 'Delivered',
  charges:2000,
    gst:7,
},
{
  Id: 2580,
  Name: 'Running Socks',
  Image:require('../Assets/Running_Socks.jpg'),
  company: 'Decathlon',
  sku: 'DEC-FW-2580',
  Department: 'Fashion',
  category: 'Footwear',
  gender:'Unisex',
  size:{'S':100,'M':50,'L':100,'XL':50},
  description: 'Sweat-resistant running socks with cushioned sole.',
  warehouse: 2,
  stock: 300,
  price: 400,
  currency: 'INR',
  discount: 5,
  rating: 4.1,
  supplier: 'Decathlon Sports India',
  ordered_Date: dayAgo(10),
  status: 'Shipped',
  charges:2800,
  gst:7,
},
];

export { Ordersdata };
